### ISSUE TITLE
download location other then micro$oft store

### ISSUE THREAD

**Issue by nutpantz** [torum/MPDCtrl#15]
many people ( and  LOT who like opensource) really like a download location other then the micro$oft store

**Comment by Cornelius-Figgle** [comment]
I second this, distributing standalone EXEs as well as package managers such as Scoop would be preferable. If you can distribute EXEs via the GitHub releases, then others (myself included), can package it for Scoop etc

**Comment by nutpantz** [comment]
403 - Forbidden

**Comment by torum** [comment]
You can now download executables directly from the [releases page](https://github.com/torum/MPDCtrl/releases) (asset section). Thank you!
