### ISSUE TITLE
Confirm Remove Selected dialog doesn't get focus

### ISSUE THREAD

**Issue by asktoby** [torum/MPDCtrl#18]
In the Queue tab, if you multiselect many songs, then press Ctrl-Del to remove them, the dialog that appears doesn't get focus, so if you press return, it jumps to somewhere else in the playlist rather than removing the items.

![image](https://github.com/torum/MPDCtrl/assets/129841/62c49c33-1484-4e2d-be3a-8a1dd3c30fc5)

**Comment by torum** [comment]
Thank you very much for your feedback and very sorry for the very long delay in response...
Confirmed and fixed in v3.1.1.
Thank you again.
