### ISSUE TITLE
Can't use DNS name as host

### ISSUE THREAD

**Issue by krendil** [torum/MPDCtrl#6]
I have DNS set up on my local network to make it easier to connect my devices. However, if I enter the DNS name of my MPD server as the host when setting up a profile, it gives the error "Invalid address format."

Looking at the code [MainViewModel.cs](https://github.com/torum/MPDCtrl/blob/52c4707ccaaedbe68e549b75b63c9b94470267ed/MPDCtrl-Desktop/MPDCtrl/ViewModels/MainViewModel.cs#L2334-L2368), it appears the this application only accepts IP addresses and the string "localhost".

This is a feature request to be able to set any DNS name as the host when setting up a profile.

**Comment by torum** [comment]
Hi! Thank you for your suggestion. Yes, you are right MPDCtrl currently only accepts IP addresses or the hardcoded "localhost". And I agree that it would be much better if it accepts DNS names as well. It was in my TODO list in the beginning but I kind of forgot about that. Now that you mentioned it, it's back in. But I'm not sure when I'm able to work on it. It may take some time. Thanks.

**Comment by torum** [comment]
Hi! Sorry it took a long time, but I updated the app. Now, you can input hostnames. Hope you like it.
